name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up ROS 2
        run: |
          apt-get update
          apt-get install git -y
                 
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_weather_ws/src/weather_pkg/
          cd /root/ros2_weather_ws
          bash -xv ./src/weather_pkg/test/test.bash /root
