name: Test WeatherNode

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # ROS2と依存関係をセットアップ
      - name: Set up ROS 2 Humble
        run: |
          sudo apt update
          sudo apt install -y curl gnupg2 lsb-release
          curl -sSL http://repo.ros2.org/repos/ros2/ubuntu/gpg | sudo tee /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
          sudo apt update
          sudo apt install -y ros-humble-desktop
          source /opt/ros/humble/setup.bash

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests
          pip install rclpy

      - name: Set up environment variable for OpenWeatherMap API key
        run: |
          echo "OPENWEATHERMAP_API_KEY=y7c8ebb86284de8568f27c0e05f1cd4ac" >> $GITHUB_ENV

      - name: Run Python test (weather_node)
        run: |
          # Execute the weather node in the background (use & to run it in the background)
          source /opt/ros/humble/setup.bash
          python3 -c "import rclpy; from weather_pkg.weather_node import WeatherNode; rclpy.init(); node = WeatherNode(); rclpy.spin_once(node, timeout_sec=1); node.destroy_node(); rclpy.shutdown()"


