name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-test:
    name: Python Package Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Tests
        run: |
          pytest

  ros2-test:
    name: ROS 2 Package Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS 2
        run: |
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions

      - name: Install ROS 2 dependencies
        run: |
          vcs import < ros2.repos
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build ROS 2 packages
        run: colcon build

      - name: Run ROS 2 tests
        run: colcon test --event-handlers console_cohesion+

      - name: Check ROS 2 test results
        run: colcon test-result

