name: ROS 2 Package Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 environment
        run: |
          sudo apt update && sudo apt install -y \
            ros-humble-desktop \
            python3-colcon-common-extensions

      - name: Install dependencies
        run: |
          sudo apt update && rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build workspace
        run: |
          colcon build --symlink-install

      - name: Run tests
        run: |
          colcon test
          colcon test-result --verbose

