- name: Set up ROS 2
  run: |
    # 必要なツールをインストール
    sudo apt update
    sudo apt install -y curl gnupg2 lsb-release

    # ROS2の署名キーを保存
    curl -sSL http://repo.ros2.org/repos/ros2/ubuntu/gpg | sudo tee /usr/share/keyrings/ros-archive-keyring.gpg

    # ROS2のリポジトリを追加 (ここでは手動でコードネーム 'jammy' を指定)
    echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list

    # パッケージリストを更新
    sudo apt update

    # ROS2のデスクトップパッケージをインストール
    sudo apt install -y ros-humble-desktop

    # ROS 2のセットアップ
    source /opt/ros/humble/setup.bash

