name: Test Weather Node

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make test script executable
      run: chmod +x ./test.bash

    - name: Run test script
      env:
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      run: ./test.bash ${{ secrets.OPENWEATHERMAP_API_KEY }}
