name: test
on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:foxy

    steps:
      - uses: actions/checkout@v2

      - name: Install rsync
        run: |
          apt-get update
          apt-get install -y rsync

      - name: build and test
        run: |
          mkdir -p /root/ros2_weather_ws/src/weather_pkg
          rsync -av ./ /root/ros2_weather_ws/src/weather_pkg/
          cd /root/ros2_weather_ws
          bash -xv ./src/weather_pkg/test/test.bash /root

