name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:foxy

    steps:
      - uses: actions/checkout@v2

      - name: Install ROS 2 dependencies
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions python3-rosdep
          rm -f /etc/ros/rosdep/sources.list.d/20-default.list
          rosdep init
          rosdep update

      - name: Install rsync
        run: |
          apt-get update
          apt-get install -y rsync

      - name: build and test
        run: |
          mkdir -p /root/ros2_weather_ws/src/weather_pkg
          rsync -av ./ /root/ros2_weather_ws/src/weather_pkg/
          cd /root/ros2_weather_ws
          bash -xv ./src/weather_pkg/test/test.bash /root

