name: test
on: push
jobs:
        test:
                runs-on: ubuntu-22.04
                container: ryuichiueda/ubuntu22.04-ros2:latest
                steps:
                        - uses: actions/checkout@v2
                          - name: build and test
                            run: |
                                     rsync -av ./ /root/ros2_weather_ws/src/weather_pkg/
                                     cd /root/ros2_weather_ws
                                     bash -xv ./src/ros2_weather_ws/test/test.bash /root
