name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:foxy

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y rsync python3-pip
          pip3 install --upgrade pip  # pipを最新にアップグレード
          pip3 install pytest  # pytestをインストール
        shell: bash

      - name: Check pytest installation
        run: |
          pip3 list  # インストールされたパッケージをリスト表示
          pytest --version || echo "pytest not found"  # pytestのインストール確認
        shell: bash

      - name: Set up ROS 2 workspace
        run: |
          source /opt/ros/foxy/setup.bash
          mkdir -p /root/ros2_weather_ws/src
        shell: bash

      - name: Copy source code to workspace
        run: |
          rsync -av ./ /root/ros2_weather_ws/src/weather_pkg/
        shell: bash

      - name: Install dependencies
        run: |
          source /opt/ros/foxy/setup.bash
          rosdep update
          rosdep install --from-paths /root/ros2_weather_ws/src --ignore-src -r -y
        shell: bash

      - name: Build the package
        run: |
          source /opt/ros/foxy/setup.bash
          cd /root/ros2_weather_ws
          colcon build --symlink-install
        shell: bash

      - name: Run tests
        run: |
          source /opt/ros/foxy/setup.bash
          cd /root/ros2_weather_ws
          pytest src/weather_pkg/test/test_weather_node.py
        shell: bash

