name: test
on: push
jobs:
        test:
                runs-on: ubuntu-22.04
                container: ros:foxy
                steps:
                        - uses: actions/checkout@v2
                        - name: build and test
                          run: |
                                  rsync -av ./ /root/ros2_weather_ws/src/weather_pkg/
                                  cd /root/ros2_weather_ws
                                  bash -xv ./src/weather_pkg/test/test.bash /root

