name: ROS2 Weather Node Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ROS 2
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions python3-pip
          pip install -r requirements.txt

      - name: Build and test package
        run: |
          source /opt/ros/foxy/setup.bash
          source /root/ros2_weather_ws/install/setup.bash
          cd /root/ros2_weather_ws
          colcon build --packages-select weather_pkg
          pytest src/weather_pkg/test/test_weather_node.py

