name: test

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:foxy

    steps:
      - uses: actions/checkout@v2

      - name: Set up ROS 2 workspace
        run: |
          source /opt/ros/foxy/setup.bash
          mkdir -p /root/ros2_weather_ws/src
          
      - name: Copy source code to workspace
        run: |
          rsync -av ./ /root/ros2_weather_ws/src/weather_pkg/

      - name: Install dependencies
        run: |
          source /opt/ros/foxy/setup.bash
          rosdep update
          rosdep install --from-paths /root/ros2_weather_ws/src --ignore-src -r -y

      - name: Build the package
        run: |
          source /opt/ros/foxy/setup.bash
          cd /root/ros2_weather_ws
          colcon build --symlink-install

      - name: Run tests
        run: |
          source /opt/ros/foxy/setup.bash
          cd /root/ros2_weather_ws
          bash -xv ./src/weather_pkg/test/test.bash /root

