name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-tests:
    name: Python Package Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Python tests
      run: |
        pytest test/

  ros2-tests:
    name: ROS 2 Package Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS 2 (Humble)
      run: |
        sudo apt update && sudo apt install -y curl
        curl -sSL https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos -o ros2.repos
        vcs import src < ros2.repos
        sudo apt update && sudo apt install -y \
          build-essential cmake python3-colcon-common-extensions \
          python3-rosdep python3-vcstool git
        sudo rosdep init
        rosdep update

    - name: Install dependencies
      run: |
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build and Test ROS 2 Package
      run: |
        colcon build
        colcon test --event-handlers console_cohesion+

    - name: Check test results
      run: colcon test-result --all

