name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:foxy

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y rsync python3-pip
          python3 -m pip install --upgrade pip  # pipを最新にアップグレード
          python3 -m pip install pytest  # pytestをインストール
        shell: bash

      - name: Check pytest installation
        run: |
          python3 -m pytest --version || echo "pytest not found"  # pytestバージョン確認
          pip3 list  # インストールされたパッケージをリスト表示
        shell: bash

      - name: Set up ROS 2 workspace
        run: |
          source /opt/ros/foxy/setup.bash
          mkdir -p /root/ros2_weather_ws/src
        shell: bash

      - name: Copy source code to workspace
        run: |
          rsync -av ./ /root/ros2_weather_ws/src/weather_pkg/
        shell: bash

      - name: Check the contents of the /root/ros2_weather_ws/src/weather_pkg directory
        run: |
          ls -l /root/ros2_weather_ws/src/weather_pkg  # weather_pkgディレクトリ内のファイルを確認
        shell: bash

      - name: Check the contents of the /root/ros2_weather_ws/src/weather_pkg/test directory
        run: |
          ls -l /root/ros2_weather_ws/src/weather_pkg/test  # testディレクトリ内のファイルを確認
        shell: bash

      - name: Install dependencies
        run: |
          source /opt/ros/foxy/setup.bash
          rosdep update
          rosde

